/*
 * This file is generated by jOOQ.
 */
package net.tirasa.test.mavenproject1.model;


import net.tirasa.test.mavenproject1.model.tables.Article;
import net.tirasa.test.mavenproject1.model.tables.Author;
import net.tirasa.test.mavenproject1.model.tables.records.ArticleRecord;
import net.tirasa.test.mavenproject1.model.tables.records.AuthorRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ArticleRecord> ARTICLE_PKEY = Internal.createUniqueKey(Article.ARTICLE, DSL.name("article_pkey"), new TableField[] { Article.ARTICLE.ID }, true);
    public static final UniqueKey<AuthorRecord> AUTHOR_PKEY = Internal.createUniqueKey(Author.AUTHOR, DSL.name("author_pkey"), new TableField[] { Author.AUTHOR.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ArticleRecord, AuthorRecord> ARTICLE__FK_AUTHOR_ID = Internal.createForeignKey(Article.ARTICLE, DSL.name("fk_author_id"), new TableField[] { Article.ARTICLE.AUTHOR_ID }, Keys.AUTHOR_PKEY, new TableField[] { Author.AUTHOR.ID }, true);
}
