/*
 * This file is generated by jOOQ.
 */
package net.tirasa.test.mavenproject1.model;


import net.tirasa.test.mavenproject1.model.tables.Article;
import net.tirasa.test.mavenproject1.model.tables.Author;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.article</code>.
     */
    public static final Article ARTICLE = Article.ARTICLE;

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;
}
