/*
 * This file is generated by jOOQ.
 */
package net.tirasa.test.mavenproject1.model.tables.records;


import net.tirasa.test.mavenproject1.model.tables.Article;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ArticleRecord extends UpdatableRecordImpl<ArticleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.article.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.article.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.article.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.article.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.article.author_id</code>.
     */
    public void setAuthorId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.article.author_id</code>.
     */
    public Integer getAuthorId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleRecord
     */
    public ArticleRecord() {
        super(Article.ARTICLE);
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
    public ArticleRecord(Integer id, String title, String description, Integer authorId) {
        super(Article.ARTICLE);

        setId(id);
        setTitle(title);
        setDescription(description);
        setAuthorId(authorId);
        resetChangedOnNotNull();
    }
}
